name: build
on:
  push:
    branches:
      - "master"
    tags:
      - "!*"
  pull_request:
    branches:
      - "*"
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: -E golint -E bodyclose
  build:
    runs-on: ubuntu-latest
    name: build
    needs: linting
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get dependencies
        run: make deps
      - name: Build & Test
        run: make build
      - name: Validate release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --snapshot --skip-publish --rm-dist
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "whyeasy/jira-exporter:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
